job('Maven_Project_Via_DSL_01'){
    description("Maven job generated by the DSL on ${new Date()}, this project is a small Maven project hosted on github")
    scm {
        git("https://github.com/smranjan/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //Archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}